# .github/workflows/scheduled-builds.yml
name: CRON Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Cron Schedule
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job ran"
