# .github/workflows/scheduled-builds.yml
name: CRON Schedule

on:
  schedule:
    branches: [master]
    - cron: '*/5 * * * *'
jobs:
  merge-master-to-datadog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout datadog
          git pull
          git merge --no-ff master -m "Auto-merge master back to datadog"
          git push
